spring:
  profiles:
    active: local
    include: oauth
  messages:
    basename: i18n/exception
    encoding: UTF-8
  social:
    kakao:
      client_id: cae60ae3e01a5b8a74c0ddb02f2c4f21 # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  jwt:
    secret: govlepel@$&amp;
  url:
    base: http://localhost:3000

