logging:
  level:
    root: warn
    me.jung.demokakaoapi: debug
    org.hibernate.type.descriptor.sql: trace
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/demokakao
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    showSql: true
